version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db1
      - postgres_db2

  postgres_db1:
    image: postgres:13
    volumes:
      - ./your-init-script.sh:/docker-entrypoint-initdb.d/your-init-script.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
  postgres_db2:
    image: postgres:13
    volumes:
      - ./your-init-script.sh:/docker-entrypoint-initdb.d/your-init-script.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db2
    ports:
      - "5433:5432"