version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=postgres://postgres:postgres@db1:5432/db1
    ports:
      - "8080:8080"

  db1:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db1
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data

  db2:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db2
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data

volumes:
  db1_data:
  db2_data: